apiVersion: v1
data:
  special.keyid: xxxx******
  special.keysecret: xxxx******
kind: ConfigMap
metadata:
  name: cloud-config-sk
  namespace: kube-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-controller-manager
  namespace: kube-system
data:
  cloud-controller-manager.conf: |-
    kind: Config
    contexts:
    - context:
        cluster: kubernetes
        user: system:cloud-controller-manager
      name: system:cloud-controller-manager@kubernetes
    current-context: system:cloud-controller-manager@kubernetes
    users:
    - name: system:cloud-controller-manager
      user:
        tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: xxxxx*************************************
        server: http://172.17.15.222:60001
      name: kubernetes1
  cloud-config.json: |
    {
        "Global":{"clusterID": "codis-admin"}
    }
