// +build !ignore_autogenerated

/*
Copyright 2019 fangjianfeng.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodisCluster) DeepCopyInto(out *CodisCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodisCluster.
func (in *CodisCluster) DeepCopy() *CodisCluster {
	if in == nil {
		return nil
	}
	out := new(CodisCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CodisCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodisClusterList) DeepCopyInto(out *CodisClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CodisCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodisClusterList.
func (in *CodisClusterList) DeepCopy() *CodisClusterList {
	if in == nil {
		return nil
	}
	out := new(CodisClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CodisClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodisClusterSpec) DeepCopyInto(out *CodisClusterSpec) {
	*out = *in
	in.RedisSpec.DeepCopyInto(&out.RedisSpec)
	in.DashboardSpec.DeepCopyInto(&out.DashboardSpec)
	in.FeSpec.DeepCopyInto(&out.FeSpec)
	in.HaSpec.DeepCopyInto(&out.HaSpec)
	in.ProxySpec.DeepCopyInto(&out.ProxySpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodisClusterSpec.
func (in *CodisClusterSpec) DeepCopy() *CodisClusterSpec {
	if in == nil {
		return nil
	}
	out := new(CodisClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodisClusterStatus) DeepCopyInto(out *CodisClusterStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodisClusterStatus.
func (in *CodisClusterStatus) DeepCopy() *CodisClusterStatus {
	if in == nil {
		return nil
	}
	out := new(CodisClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodisDashboardSpec) DeepCopyInto(out *CodisDashboardSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.LifeCycle != nil {
		in, out := &in.LifeCycle, &out.LifeCycle
		*out = new(corev1.Lifecycle)
		(*in).DeepCopyInto(*out)
	}
	in.Requires.DeepCopyInto(&out.Requires)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodisDashboardSpec.
func (in *CodisDashboardSpec) DeepCopy() *CodisDashboardSpec {
	if in == nil {
		return nil
	}
	out := new(CodisDashboardSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodisFeSpec) DeepCopyInto(out *CodisFeSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.LifeCycle != nil {
		in, out := &in.LifeCycle, &out.LifeCycle
		*out = new(corev1.Lifecycle)
		(*in).DeepCopyInto(*out)
	}
	in.Requires.DeepCopyInto(&out.Requires)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodisFeSpec.
func (in *CodisFeSpec) DeepCopy() *CodisFeSpec {
	if in == nil {
		return nil
	}
	out := new(CodisFeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodisHaSpec) DeepCopyInto(out *CodisHaSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.LifeCycle != nil {
		in, out := &in.LifeCycle, &out.LifeCycle
		*out = new(corev1.Lifecycle)
		(*in).DeepCopyInto(*out)
	}
	in.Requires.DeepCopyInto(&out.Requires)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodisHaSpec.
func (in *CodisHaSpec) DeepCopy() *CodisHaSpec {
	if in == nil {
		return nil
	}
	out := new(CodisHaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodisProxySpec) DeepCopyInto(out *CodisProxySpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.LifeCycle != nil {
		in, out := &in.LifeCycle, &out.LifeCycle
		*out = new(corev1.Lifecycle)
		(*in).DeepCopyInto(*out)
	}
	in.Requires.DeepCopyInto(&out.Requires)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodisProxySpec.
func (in *CodisProxySpec) DeepCopy() *CodisProxySpec {
	if in == nil {
		return nil
	}
	out := new(CodisProxySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodisRedisSpec) DeepCopyInto(out *CodisRedisSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.LifeCycle != nil {
		in, out := &in.LifeCycle, &out.LifeCycle
		*out = new(corev1.Lifecycle)
		(*in).DeepCopyInto(*out)
	}
	in.CodisServerRequires.DeepCopyInto(&out.CodisServerRequires)
	in.CodisServerExporterRequires.DeepCopyInto(&out.CodisServerExporterRequires)
	in.BackupCronJob.DeepCopyInto(&out.BackupCronJob)
	in.StorageRequires.DeepCopyInto(&out.StorageRequires)
	if in.RedisConf != nil {
		in, out := &in.RedisConf, &out.RedisConf
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodisRedisSpec.
func (in *CodisRedisSpec) DeepCopy() *CodisRedisSpec {
	if in == nil {
		return nil
	}
	out := new(CodisRedisSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronJobSpec) DeepCopyInto(out *CronJobSpec) {
	*out = *in
	if in.StartingDeadlineSeconds != nil {
		in, out := &in.StartingDeadlineSeconds, &out.StartingDeadlineSeconds
		*out = new(int64)
		**out = **in
	}
	if in.SuccessfulJobsHistoryLimit != nil {
		in, out := &in.SuccessfulJobsHistoryLimit, &out.SuccessfulJobsHistoryLimit
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronJobSpec.
func (in *CronJobSpec) DeepCopy() *CronJobSpec {
	if in == nil {
		return nil
	}
	out := new(CronJobSpec)
	in.DeepCopyInto(out)
	return out
}
