# permissions to do edit codisclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: codiscluster-editor-role
rules:
- apiGroups:
  - k8s.infra.cn
  resources:
  - codisclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.infra.cn
  resources:
  - codisclusters/status
  verbs:
  - get
  - patch
  - update
