# permissions to do viewer codisclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: codiscluster-viewer-role
rules:
- apiGroups:
  - k8s.infra.cn
  resources:
  - codisclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.infra.cn
  resources:
  - codisclusters/status
  verbs:
  - get
