apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: v1.8.0
  name: kube-state-metrics
  namespace: kube-system
spec:
  type: NodePort
  ports:
    - name: http-metrics
      port: 8080
      nodePort: 9080
      protocol: TCP
      targetPort: 8080
    - name: telemetry
      port: 8081
      nodePort: 9081
      protocol: TCP
      targetPort: 8081
  selector:
    app.kubernetes.io/name: kube-state-metrics
