{
 "title": "redis-monitor",
 "description": "Prometheus dashboard for Redis servers (by host and alias)",
 "tags": [
  "prometheus",
  "redis"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "service", "label": "service", "query": "label_values(redis_up, app)" }
  ]
 },
 "panels": [
  {
   "title": "client connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "redis_connected_clients{app=~\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "key rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total{app=~\"$service\"}[1m]) / (irate(redis_keyspace_hits_total{app=~\"$service\"}[1m]) + (irate(redis_keyspace_misses_total{app=~\"$service\"}[1m])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "mem used-percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "redis_memory_used_bytes{app=~\"$service\"} / redis_memory_max_bytes{app=~\"$service\"} ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "redis cmd",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_commands_processed_total{app=~\"$service\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network I/O - input",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_net_input_bytes_total{app=~\"$service\"}[1m]))",
     "legendFormat": "{{ instance }} "
    }
   ]
  },
  {
   "title": "Network I/O - output",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_net_output_bytes_total{app=~\"$service\"}[1m]))",
     "legendFormat": "{{ instance }} "
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5,rate(redis_db_keys{app=~\"$service\"}[1m]))",
     "legendFormat": "{{instance}} - {{db}}"
    }
   ]
  },
  {
   "title": "timeout key total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{app=~\"$service\"}[1m])) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "cumulative key total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_evicted_keys_total{app=~\"$service\"}[1m])) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "mget / QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_commands_total{app=\"$service\", cmd=\"mget\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "set / QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_commands_total{app=~\"$service\", cmd=\"set\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "del / QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_commands_total{app=~\"$service\", cmd=\"del\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}