---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: monitor-service
  labels:
    app: monitor-service
spec:
  type: NodePort
  ports:
    - name: prometheus
      port: 9090
      nodePort: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: monitor
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |-
    scrape_configs:
    - job_name: 'kubernetes-pods'
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      kubernetes_sd_configs:
      - role: pod

      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port]
        regex: "9121|8080"
        action: keep

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor
spec:
  selector:
    matchLabels:
      app: monitor
  replicas: 1
  template:
    metadata:
      labels:
        app: monitor
    spec:
      serviceAccountName: prometheus
      serviceAccount: prometheus
      terminationGracePeriodSeconds: 60
      containers:
        - name: prometheus
          image: prom/prometheus:v2.11.0
          imagePullPolicy: IfNotPresent
          args:
            - "--config.file=/data/service/prometheus/conf/prometheus.yml"
            - "--web.console.libraries=/usr/share/prometheus/console_libraries"
            - "--web.console.templates=/usr/share/prometheus/consoles"
            - "--web.enable-lifecycle"
            - "--web.listen-address=:9090"
          ports:
            - containerPort: 9090
              name: prometheus
          volumeMounts:
            - mountPath: /etc/localtime
              name: timezone
              readOnly: true
            - name: prometheus-config
              mountPath: /data/service/prometheus/conf/
          resources:
            limits:
              memory: "48Gi"
              cpu: "4"

      volumes:
        - name: timezone
          hostPath:
            path: /etc/localtime
            type: File
        - name: prometheus-config
          configMap:
            name: prometheus-config
